### ISSUE TITLE
services export的问题

### ISSUE THREAD

**Issue by chy083** [sumnow/vue-templates#2]
### Version
1.1.6

### What is expected?
services 导出是不是可以换成多对象导出的方式

    export {appIn, appIn2}

目前是

   export default obj

这样会引入额外的接口处理函数吧。

调用方式也是

obj.appIn({url,params,method})

**Comment by sumnow** [comment]
![image](https://user-images.githubusercontent.com/23467500/37019010-8d05b542-2151-11e8-8a2f-69661b2f7575.png)


这个问题，已经在1.1.8种提出了解决的方法，放开注释即可。
